### ISSUE TITLE
namespace not present in attributes

### ISSUE THREAD

**Issue by fgravin** [highsource/jsonix#102]
Hello,

I think this is a bug, we try to encode an element that should result (regardless specifications) to
`<ows:boundingbox ows:projection="EPSG:4326">` but it is encoded this way `<ows:boundingbox projection="EPSG:4326">` where the namespace `ows` is not used for the `projection` attribute.

**Comment by highsource** [comment]
Could you please provide a reproducing test?

**Comment by arnaud-morvan** [comment]
Hello,

here is a more precise description of the problem: 

We use jsonix to marshal WPS request body, which contains an "BoundingBoxData" element with an "dimensions" attribute. After marshalling, the "dimensions" attribute is not prefixed with ows namespace, and the pyWPS server doesn't recognize it.

For myself, I think that like "boundingBoxData" element is of type "ows:BoundingBoxDataType" the ows namespace on dimensions attribute should not be mandatory.

here is the json part for the wps:BoundingBoxData element (which is of type ows:BoundingBoxDataType):

    "boundingBoxData": {
        "dimensions": 2,
        "lowerCorner": ["-9.38", "47.33"],
        "upperCorner": ["-7.27", "48.59"]
    }

here is the XML produced by jsonix:

    <wps:BoundingBoxData dimensions="2">
        <ows:LowerCorner>-9.38 47.33</ows:LowerCorner>
        <ows:UpperCorner>-7.27 48.59</ows:UpperCorner>
    </wps:BoundingBoxData>

here is the wps:BoundingBoxData element schema (from: http://schemas.opengis.net/wps/1.0.0/wpsExecute_request.xsd)

    <element name="BoundingBoxData" type="ows:BoundingBoxType">
        <annotation>
            <documentation>Identifies this input or output data as an ows:BoundingBox data structure, and provides that ows:BoundingBox data. </documentation>
        </annotation>
    </element>

and we find the ows:BoundingBoxType in http://schemas.opengis.net/ows/1.1.0/owsCommon.xsd

    <complexType name="BoundingBoxType">
        <annotation>
            <documentation>XML encoded minimum rectangular bounding box (or region) parameter, surrounding all the associated data. </documentation>
            <documentation>This type is adapted from the EnvelopeType of GML 3.1, with modified contents and documentation for encoding a MINIMUM size box SURROUNDING all associated data. </documentation>
        </annotation>
        <sequence>
            <element name="LowerCorner" type="ows:PositionType">
                <annotation>
                    <documentation>Position of the bounding box corner at which the value of each coordinate normally is the algebraic minimum within this bounding box. In some cases, this position is normally displayed at the top, such as the top left for some image coordinates. For more information, see Subclauses 10.2.5 and C.13. </documentation>
                </annotation>
            </element>
            <element name="UpperCorner" type="ows:PositionType">
                <annotation>
                    <documentation>Position of the bounding box corner at which the value of each coordinate normally is the algebraic maximum within this bounding box. In some cases, this position is normally displayed at the bottom, such as the bottom right for some image coordinates. For more information, see Subclauses 10.2.5 and C.13. </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="crs" type="anyURI" use="optional">
            <annotation>
                <documentation>Usually references the definition of a CRS, as specified in [OGC Topic 2]. Such a CRS definition can be XML encoded using the gml:CoordinateReferenceSystemType in [GML 3.1]. For well known references, it is not required that a CRS definition exist at the location the URI points to. If no anyURI value is included, the applicable CRS must be either: a) Specified outside the bounding box, but inside a data structure that includes this bounding box, as specified for a specific OWS use of this bounding box type. b) Fixed and specified in the Implementation Specification for a specific OWS use of the bounding box type. </documentation>
            </annotation>
        </attribute>
        <attribute name="dimensions" type="positiveInteger" use="optional">
            <annotation>
                <documentation>The number of dimensions in this CRS (the length of a coordinate sequence in this use of the PositionType). This number is specified by the CRS definition, but can also be specified here. </documentation>
            </annotation>
        </attribute>
    </complexType>

**Comment by highsource** [comment]
Your original report was mentioning `ows:projection`, I see not `projection` in the schema. Is this still an issue?

As for `ows:dimensions`. The [schema you refer to](http://schemas.opengis.net/ows/1.1.0/owsCommon.xsd) does not have `attributeFormDefault="qualified"`, so it defaults to `unqualified`. This would mean that the `dimensions` attribute will belong to the empty namespace, so `dimensions` would be correct and `ows:dimensions` not. For me it looks that

```
<wps:BoundingBoxData dimensions="2">
    <ows:LowerCorner>-9.38 47.33</ows:LowerCorner>
    <ows:UpperCorner>-7.27 48.59</ows:UpperCorner>
</wps:BoundingBoxData>
```

is correct. According to schema, it should be `dimensions`, not `ows:dimensions`. So I guess the problem is in the pyWPS server. I think you should report an issue there.

**Comment by arnaud-morvan** [comment]
Thanks for your response, I was not aware of attributeFormDefault attribute.
The problem is on the server side, I've filled a ticket accordingly.
This could be closed.
