### ISSUE TITLE
pattern in XML schema don't get carried over into JSON schema

### ISSUE THREAD

**Issue by coderextreme** [highsource/jsonix#106]
I'm trying to carry over the regular expression patterns from this XML schema below into JSON schema so I can validate JSON documents.  Does JSON schema handle regular expressions?  If so, can Jsonix?  If not, can we create an extension to JSON schema that Jsonix can support?   Thanks!

http://www.web3d.org/specifications/x3d-3.4.xsd

**Comment by highsource** [comment]
Hi,

I think JSON Schema supportes patterns (regular expressions):

http://spacetelescope.github.io/understanding-json-schema/reference/string.html#regular-expressions

The compiler does not support this, however.
If JSON Schema and XML Schema have identical regex syntaxes then it will be
possible, if not then not (as I most probably won't be able to translate
regex languages).

Best wishes,
Alexey

**Comment by highsource** [comment]
Closing here.

**Comment by coderextreme** [comment]
Could the regular expression schema contain the regular expression
language, similar to http content type or script tags in html?

**Comment by coderextreme** [comment]
I think most of our regexps are numbers. Some are colors.  We don't
currently use xs:list in XSD so these aren't being translated to numeric
arrays in JSONIX output.  Should we create a derivative of our XSD which
has xs:list to get the numeric arrays, or is there a better way?

**Comment by highsource** [comment]
> Could the regular expression schema contain the regular expression
language, similar to http content type or script tags in html?

That wouldn't bring much unless someone really translates regexp dialects one into another.

> I think most of our regexps are numbers. Some are colors.  We don't currently use xs:list in XSD so these aren't being translated to numeric arrays in JSONIX output.  Should we create a derivative of our XSD which has xs:list to get the numeric arrays, or is there a better way?

Sorry, I don't understand the question.

I'm closing this issue as we should move discussions on this issue to the `jsonix-schema-compiler` project.
