### ISSUE TITLE
JSON Schema enum values not generated

### ISSUE THREAD

**Issue by vzhukovskyy** [highsource/jsonix#110]
JSON Schema, generated from XSD below is missing enum values

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:simpleType name="DayOfWeek">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Mon" />
			<xs:enumeration value="Tue" />
			<xs:enumeration value="Wed" />
			<xs:enumeration value="Thu" />
			<xs:enumeration value="Fri" />
			<xs:enumeration value="Sat" />
			<xs:enumeration value="Sun" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

**Comment by highsource** [comment]
Hi,

schema compilation is in scope of `highsource/jsonix-schema-compiler`.

This issue is already known:

highsource/jsonix-schema-compiler#38

Best wishes,
Alexey
