### ISSUE TITLE
Some tests fails if not UTC

### ISSUE THREAD

**Issue by sampov2** [highsource/jsonix#112]
In trying to build jsonix, I found that some tests fail if local time is not in UTC. I've attached the surefire report target/surefire-reports/org.hisrc.jsonix.test.JsonixTest.txt

If I set the timezone to UTC, this test passes.

[org.hisrc.jsonix.test.JsonixTest.txt](https://github.com/highsource/jsonix/files/55351/org.hisrc.jsonix.test.JsonixTest.txt)

**Comment by highsource** [comment]
Should be fixed now.
