### ISSUE TITLE
Leveraging jsonix in a wysiwyg editor

### ISSUE THREAD

**Issue by murrayju** [highsource/jsonix#137]
This is more of a question than an issue, let me know if there is a better place to ask this.

I am working on a wysiwyg editor for a document format with a strict structure backed by a xsd schema. What I am hoping to accomplish is to leverage the schema in a way that ensures that all edits result in a valid document. A particularly interesting problem is copy/paste. Given some target node (the cursor position), is it valid to insert some arbitrary xml fragment at this position (and if not, what's the nearest parent/sibling location that *is* valid)?

jsonix seems to have the ability to transform a xsd into some js objects, but I haven't found much documentation on how these might be leveraged (aside from marshalling/unmarshalling). Do you have any advice on if/how I could leverage jsonix to accomplish my goal?

**Comment by highsource** [comment]
You basically need some kind of a model. You need to know what's allowed and what's not, for instance which properties a certain type has, their properties, cardinalities etc.

For this, you can use Jsonix mappings which implement this very model. Jsonix mappings model complex and simple types, properties, cardinalities and so on. When you create a Jsonix context, it builds this model from the provided mappings and then uses it to unmarshal or marshal.

You can use this model to inspect type information in the runtime. You can quite find type info by name and then find out which properties it has (if it's a complex type) and so on. This will allow you to either build your UI from the model or solve other tasks like copy-paste.

To take the copy/paste case, you'll need to know the type of the target node and the type of the object in the buffer. Both are quite easy to do with the right organisation. For instance, after unmarshalling, Jsonix keeps the type name as the `TYPE_NAME` property. You could do something similar. When matching, you can also leverage the inheritance info, for instance to allo pasting subclass where superclass allowed, effectively implementing polymorphism.

Several years ago I've implemented an XML Schema-driven UI generator, so I'm absolutely positive it would be possible with Jsonix as Jsonix now provides much clearer and better model than anything I had back then. I think the devil will be in details, but that's a different story.

Sorry, I can't provide code samples and pointer apart from those already contained in the code base and wiki. My advise would be to start with a very simple schema (check purchase order in examples) and try to access type information in tests. Like, enumerate properties and their types and so on. This will give you the idea of how it works. Start by searching for something like `getTypeInfo` in tests:

https://github.com/highsource/jsonix/tree/master/nodejs/scripts/tests

Hope this helps.
