### ISSUE TITLE
Duration parsed from "PT0S" print "P" not a valid duration

### ISSUE THREAD

**Issue by amarant** [highsource/jsonix#141]
When jsonix parse the duration "PT0S" it will generate "P", the [Xml-Schema spec specifies](https://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#duration) :

> If the number of years, months, days, hours, minutes, or seconds in any expression equals zero, the number and its corresponding designator ·may· be omitted. However, at least one number and its designator ·must· be present. 

it means at least one component part must be present. But it would be great if it was "stable", for example "P0Y", ... "PT0S" return the same value as inputted if unchanged.

**Comment by highsource** [comment]
I can follow. How about a PR?

**Comment by amarant** [comment]
Yes I will try a propose after adding some tests.

**Comment by highsource** [comment]
Great. You're right, the problem was with falsy 0 values, thanks for fixing this. I've only reworked the tests a bit, reduced them to the bare minimum. You actually don't need mappings and context to test the simple type.
