### ISSUE TITLE
Where is package.json?

### ISSUE THREAD

**Issue by stefanocudini** [highsource/jsonix#147]
It's need for NPM versioning

**Comment by highsource** [comment]
https://github.com/highsource/jsonix/blob/master/nodejs/scripts/package.json

**Comment by stefanocudini** [comment]
It might be a good idea to create a link in the Readme of the repository

**Comment by highsource** [comment]
PR welcome. :)

**Comment by stefanocudini** [comment]
PR created: https://github.com/highsource/jsonix/pull/148
