### ISSUE TITLE
[question] Changing Namespace Prefixes

### ISSUE THREAD

**Issue by Prefinem** [highsource/jsonix#152]
So currently I am trying to marshal into a string but for some reason, nothing past the body is working.  What am I doing wrong?

	var InventoryRequest = require('./mappings/' + version + '/InventoryRequest').InventoryRequest;
	var Envelope = require('./mappings/Envelope').Envelope;
	var jContext = new Jsonix.Context([InventoryRequest, Envelope], {
		namespacePrefixes: {
			"http://schemas.xmlsoap.org/soap/envelope/": "soap",
			"http://www.promostandards.org/WSDL/InventoryService/1.0.0/": "tns"
		}
	});
	var marshaller = jContext.createMarshaller();
	console.log(marshaller);
	var envelope = marshaller.marshalString({
		'soap:Envelope': {
			'body': {
				'tns:Request': {
					'wsVersion': version,
					'id': apiUsername,
					'password': apiPassword,
					'productID': ProductID,
					'productIDtype': 'Supplier'
				}
			}
		}
	});

Output

    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.promostandards.org/WSDL/InventoryService/1.0.0/"><soap:Body/></soap:Envelope>

**Comment by highsource** [comment]
Hard to say without seeing mappings. Please PR a minimal reproducing project here:

https://github.com/highsource/jsonix-support

Under `s/soap`. I never used Jsonix for SOAP, but theoretically it should work.

**Comment by Prefinem** [comment]
I have made the pull request here: https://github.com/highsource/jsonix-support/pull/10

**Comment by highsource** [comment]
Try

```
var envelope = marshaller.marshalString({
    'soap:Envelope': {
        'body': { 'any':
            'tns:Request': {
                'wsVersion': version,
                'id': apiUsername,
                'password': apiPassword,
                'productID': ProductID,
                'productIDtype': 'Supplier'
            }}
        }
    }
});
```

No guarantees but contents aren't in `body` directly, they are in the `any` property:

```
{
        localName: 'Envelope',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'header',
            elementName: 'Header',
            typeInfo: '.Header'
          }, {
            name: 'body',
            required: true,
            elementName: 'Body',
            typeInfo: '.Body'
          }, {
            name: 'any',
            minOccurs: 0,
            collection: true,
            mixed: false,
            type: 'anyElement'
          }]
      }

{
        localName: 'Body',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'any',
            minOccurs: 0,
            collection: true,
            mixed: false,
            type: 'anyElement'
          }]
      }
```

**Comment by Prefinem** [comment]
This worked for me:

	var envelope = marshaller.marshalString({
		'soap:Envelope': {
			'body': {
				'any': [{
					'tns:Request': {
						'wsVersion': apiVersion,
						'id': apiUsername,
						'password': apiPassword,
						'productID': ProductID,
						'productIDtype': 'Supplier'
					}
				}]
			}
		}
	});

Had to put an array of objects in any

Do you still want me to commit the code for support?  Even if only for an example?

**Comment by highsource** [comment]
Nope, since it worked I think it's not necessary.

**Comment by Prefinem** [comment]
Thanks a lot for the help!

**Comment by highsource** [comment]
No problem, you're welcome. :)
