### ISSUE TITLE
Thoughts on feasibility of using Jsonix for Soap Client Using WSDL

### ISSUE THREAD

**Issue by melorick** [highsource/jsonix#154]
I could not find a SoapClient library that used jsonix... is there any examples on doing this with jsonix ?

 I would like from a WSDL to be able to create a SoapClient...

Thanks,

**Comment by highsource** [comment]
Should be possible but I did not experiment with it yet.

**Comment by melorick** [comment]
the compiler seems to generate all the bindings for the wsdl... if we want to send the HTTP Post request we will need a way to wrap the soap envelope and unwrap the soap envelope... do you have any how to do this with jsonix ? or point me in a good direction ?

Regards,

**Comment by highsource** [comment]
The compiler at the moment only generates mappings for schema types and elements, not for SOAP operations.

Ulimately I think it is possible to generate a ready-to-use SOAP client with Jsonix based on WSDL. I'm not a SOAP pro so I might be wrong but here's the general outline.

From what I understand, WSDL defines operations which take some (schema-defined) XML as input and give some XML as output. This XML is payload wrapped in some SOAP envelopes and stuff. A Jsonix-based SOAP client would do the following:

* Take some nice JS/JSON data as input.
* Wrap it in a SOAP envelope.
* Marshal it in XML.
* Perform the POST request, get some XML back.
* Unmarshal the XML.
* Unwrap the payload from the response.
* Give the result back.

From these points above, Jsonix provides marshalling/unmarshalling JS<->XML.

One thing which is missing is the wrapping/unwrapping SOAP envelopes. I'd do this before converting to/from XML, so in this case you'd generates mappings for SOAP schemas and just wrap your JS payload in SOAP envelope in JS. Then Jsonix will be able to marshal/unmarshal the complete SOAP envelope with your payload in XML.

This would require compiling SOAP schemas with Jsonix Schema Compiler. This is absolutely possible, I even thing it was done already, but I could not find it.

Next, developing the SOAP client. I actually think that such a client may be generated automatically from WSDL, but for starters it would be good to provide the basic framework for developing such clients. This framework would allow configuring WSDL operations in some easy manner (mappings?) and then overtaking wrapping/marshalling/requesting/unmarshalling/unwrapping cycle. So you'd just confiure which operations take which elements/types as input and the rest would be the library's task. I think this should not be too complex for basic cases, but there's quite a lot of crazy enterprize stuff in SOAP. I'd start small and grow it to demand.

Finally once you've got the library were you can configure operations in some declarative manner, the Jsonix Schema Compiler may be extended to generate SOAP client configs automatically. The current tech in use... (TBD)

**Comment by melorick** [comment]
Thanks a lot for taking the time to answer my questions. I will try to do it that way, starting simple.

Regards,
