### ISSUE TITLE
Typescript typings generator

### ISSUE THREAD

**Issue by oehm-smith** [highsource/jsonix#156]
Are there any thoughts on generating the typings also?

**Comment by highsource** [comment]
I'm afraid that would be probably too much effort. This would require a TypeScript code model in first place (to generate correct code).

**Comment by oehm-smith** [comment]
I see that Jsonix generates `.jsonschema` files and solutions such as https://www.npmjs.com/package/json-schema-to-typescript will create typings.  Still being investigated though if it works as advertised then all will be good!

**Comment by davidspiess** [comment]
@oehm-smith were you successful with your approach?

**Comment by oehm-smith** [comment]
Ummm, too long ago :). From some distant shard of memory I recollect that it didn't work. Please try it yourself as YMMV.  The project I was working on is https://github.com/GeoscienceAustralia/GNSS-Site-Manager so maybe have a poke around in there.
