### ISSUE TITLE
Long types should unmarshall to strings

### ISSUE THREAD

**Issue by mike-marcacci** [highsource/jsonix#157]
(Moved over from https://github.com/highsource/jsonix-schema-compiler/issues/76)

Because javascript will silently limit the precision of numbers that exceed 32 bits, the `Long` and `UnsignedLong` types should unmarshall into strings instead of numbers.

**Comment by highsource** [comment]
I understand the issue but it's not that easy.
I think most people would expect `Long` and `UnsignedLong` to be numbers. Also switching to other types will breack existing applications. So I'd leave `Long` and `UnsignedLong` in mappings.

What you can do, however, is to configure you own unmarshaller/marschaller for these types. There's an example here: https://github.com/highsource/jsonix/wiki/Types:

```
var MyModule = {
    name: 'MyModule',
    typeInfos: [new(Jsonix.Class(Jsonix.Schema.XSD.AnySimpleType, {
        name: 'MyModule.YesNo',
        typeName: new Jsonix.XML.QName('urn:my', 'YesNo'),
        print: function (value) {
            Jsonix.Util.Ensure.ensureBoolean(value);
            return value ? 'yes' : 'no';
        },
        parse: function (text) {
            Jsonix.Util.Ensure.ensureString(text);
            if (text.toLowerCase() === 'yes') {
                return true;
            } else if (text.toLowerCase() === 'no') {
                return false;
            } else {
                throw "Either [yes] or [no] expected as boolean value.";
            }
        },
        CLASS_NAME: 'MyModule.YesNo'
    }))()],
    elementInfos: [{
        elementName: 'data',
        typeInfo: 'MyModule.YesNo'
    }]
};
```

Just overwrite a standard type like `Long` and `UnsignedLong` and Jsonix will use the type you configure. I even had an example of that somewhere in tests but could not find it quickly.

**Comment by mike-marcacci** [comment]
Ah, this makes sense – thanks again for pointing me in the right direction.

For anybody else searching with a similar use case, Issue #48 describes replacing a default class, and references [this test case](https://github.com/highsource/jsonix/blob/master/nodejs/tests/basic/tests/gh48.js) which is quite helpful.

To switch the behavior of the `Long` type, I simply extended the `String` class with the `Long` name after loading the mapping file:

```js
// load the generated mapping file
var mapping = require('mapping.js');

// nondestructively modify the mapping with an overridden `Long` type 
mapping = Object.assign({}, mapping, {
	typeInfos: [
		new (Jsonix.Class(Jsonix.Schema.XSD.String, {
			name : 'Long',
			typeName : Jsonix.Schema.XSD.qname('long'),
			CLASS_NAME : 'Long'
		}))()
	]
	.concat(mapping.typeInfos)
});

// create the jsonix context
var context = new Jsonix.Context([mapping]);

//...
```

Thanks again for the help and the excellent library.
