### ISSUE TITLE
Json.js demand files, wich not exist

### ISSUE THREAD

**Issue by Tusenka** [highsource/jsonix#163]
https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix.js
script demand 
https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Context/Marshaller.js file.
But folder Context doesn't exist.
Which scripts to load?

Thank you. And best regards,
Irina

**Comment by highsource** [comment]
You are not supposed to load these scripts directly. Please see
https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Your-JavaScript-Program
