### ISSUE TITLE
RangeError: Maximum call stack size exceeded  create context

### ISSUE THREAD

**Issue by TomBethoule** [highsource/jsonix#165]
Hello, 

I have an error for create context with JSONIX.

I use a XSD schema [IFC2x3.xsd](http://www.buildingsmart-tech.org/ifcXML/IFC2x3/FINAL/IFC2X3.xsd) and [ex.xsd](http://www.buildingsmart-tech.org/ifcXML/IFC2x3/FINAL/ex.xsd)

I have create the file XJB for the binding 

`<jaxb:bindings version="1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" jaxb:extensionBindingPrefixes="xjc">
    <jaxb:bindings schemaLocation="./IFC2x3.xsd" node="/xs:schema">
        <jaxb:schemaBindings>
            <jaxb:package name="PO"/>
        </jaxb:schemaBindings>
    </jaxb:bindings>
    <jaxb:bindings schemaLocation="ex.xsd" node="/xs:schema">
        <jaxb:schemaBindings>
            <jaxb:package name="POEX"/>
        </jaxb:schemaBindings>
  </jaxb:bindings> 
</jaxb:bindings>`

I create the schema PO.js and POEX.js  with this command : 

`java -jar node_modules/jsonix/lib/jsonix-schema-compiler-full.jar -d server/mappings ../ifc_schema_dev/IFC2x3.xsd -b ../ifc_schema_dev/IFC2x3.xjb `

And I try create Jsonix.Context  with this code: 

```
    var PO = require("../../../server/mappings/PO").PO;
    var POEX = require("../../../server/mappings/POEX").POEX;

    var context = new Jsonix.Context([POEX, PO]);
```

But i have this error : 

```
Exception while invoking method 'testXSD' RangeError: Maximum call stack size exceeded
I20170401-18:30:46.455(2)?     at Object.Jsonix.Util.Type.exists (C:\Users\tombe\Desktop\team-com.team.server-b94dddcaf714\blocinbl
oc-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:336:19)
I20170401-18:30:46.463(2)?     at Object.Jsonix.Context.Jsonix.Class.resolveTypeInfo (C:\Users\tombe\Desktop\team-com.team.server-b
94dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:5895:27)
I20170401-18:30:46.483(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2204:34)
I20170401-18:30:46.485(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.486(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.487(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.489(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.490(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.491(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
I20170401-18:30:46.492(2)?     at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (C:\Users\tombe\Desktop\team-com.team.server-b94
dddcaf714\team-com.team.server-b94dddcaf714\node_modules\jsonix\jsonix.js:2206:25)
```

**I think there is a circle dependence but i not find the problem. I have see the issue [144](https://github.com/highsource/jsonix/issues/114) but not work for me**

The XSD used is a official file so I think is good. Can you Help Me please? Thanks

**Comment by highsource** [comment]
Please send a PR with a test project here: https://github.com/highsource/jsonix-support/i/IFC2x3, I'll take a look.

**Comment by highsource** [comment]
Take a look at https://github.com/highsource/jsonix-support/tree/master/i/ifc2x3.

I don't know what your problem was but it worked for me. I've found an XML example, it's unmarshalled fine as far as I can see.

**Comment by TomBethoule** [comment]
I have test your sample and it's work My Problem came from XJB file. Thanks you very much
