### ISSUE TITLE
Support for marshalling CDATA content

### ISSUE THREAD

**Issue by jahow** [highsource/jsonix#173]
Hi,

Is it possible to set up a schema so that a string will be marshalled as `<![CDATA[...]]>` in the resulting XML?
If not, is this something planned or open to contribution?

Thanks for your work

**Comment by highsource** [comment]
Not at the moment. Technically there is no difference between a string and CDATA wrapping.
Open for contribution, sure. I think this can be solved with a custom simple type.

**Comment by jahow** [comment]
Actually the tricky part is to avoid encoding of special characters, which mean using `document.createCDATASection` instead of `document.createTextNode` in [Output.js](https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/XML/Output.js#L84).

I'll try to make a PR for this as it would be much cleaner than hacking it with a custom type or a string replace.

Thanks!

**Comment by highsource** [comment]
I've made a few minor changes. Mainly to check that if the text contains `]]>` it must be split in two CDATA sections as CDATA section can't contain `]]>`.
Also used `cdata` as laconic form for `asCDATA`.

Apart from that everything was fine. Thank you for your contribution!

Please check if the latest changes are fine for you.

**Comment by highsource** [comment]
https://github.com/highsource/jsonix/wiki/Properties#value-property

**Comment by jahow** [comment]
Perfect! Glad I could help improve the library. Thanks for documenting the feature.
