### ISSUE TITLE
Current status of the project

### ISSUE THREAD

**Issue by Lubo** [highsource/jsonix#174]
Hello, I wanted to use this library and I couldn't do that because I'm suffering from #171. I wanted to create a patch, but the sources seem to be duplicated and spread all around the place, with no contribution guide or guide how to build it from sources (not sure if necessary). Also, I see a large number of issues without any response. Are you aware of these issues? Are you planning on fixing that? Or is this project dead? Thank you.

**Comment by highsource** [comment]
Hi,

I'm on vacations for two weeks so I'll answer in detail then.

In short, the project is absolutely alive.

Best wishes,
Alexey

**Comment by highsource** [comment]
* The project is absolutely alive.
* In #171 I first of all need a reproducing building project using webpack2. Jsonix uses an UMD-style wrapper to be able to run in node as well in browser with thinks like RequireJS or Browserify. This breaks webpack somehow but does not seem unfixable. :) You just can't support every possible JavaScript building/packaging tool OOTB.
* JS source code is in `scripts/src/main/javascript`, the rest is "compiled" code.
* No contribution guide, correct. Was not a priority/worked without it until now.
* Build with Maven (`mvn clean install`).
* From current issues 27 are filed by me to track ideas and feature. 18 are filed by users, most are feature requests/questions, a few bugs, nothing critical from my POV.
* Yes I'm aware of issues but have to balance resources vs. criticality. Blocker bugs get fixed fast (also depending on whether there is a practical workaround). Feature requests - depending on user interest vs. feasibility.
