### ISSUE TITLE
Marshalling with a namespace and an empty prefix

### ISSUE THREAD

**Issue by nunocastromartins** [highsource/jsonix#186]
Currently, marshalling with a namespace and an empty prefix creates a default `p0` prefix:
```
<p0:purchaseOrder xmlns:p0="http://www.example.com/PO" orderDate="1999-10-20">
  ...
</p0:purchaseOrder>
```
Working example: http://jsfiddle.net/LP3DC/493/

Would it be possible to instead have the XML be generated with no prefix? I.e. generate the following:
```
<purchaseOrder xmlns="http://www.example.com/PO" orderDate="1999-10-20">
  ...
</purchaseOrder>
```
The later output is smaller and, to a human, easier to digest.
Does Jsonix natively provide any way of generating the later output?

**Side note**: I believe a saner default for the prefix (rather than `p0`) would be the module's name (i.e. `PO` in the above example).

Thank you for the awesome work so far!

**Comment by highsource** [comment]
See https://github.com/highsource/jsonix/wiki/Configuring-Namespace-Prefixes.

I think you can configure `''` as a prefix then you'll have no prefix.

**Comment by nunocastromartins** [comment]
I'm an idiot.

I did try this previously but somehow I messed up the object orded: instead of `{namespace: prefix}`, I went with `{prefix: namespace}`; of course, nothing happened then.

Thank you for your quick reply!
