### ISSUE TITLE
DateAsDate adds timezone

### ISSUE THREAD

**Issue by davidspiess** [highsource/jsonix#193]
When i parse a date as `DateAsDate`, it adds timezone informations from my local computer.
`2014-10-27` becomes `2014-10-26`, which is wrong. Is there a way to ignore the timezone and calculate it in UTC? I looked for a solution to start node.js in UTC, but this is not possible on windows.

```xml
<date>2014-10-27</date>
```

```js
  {
      type: "element",
      name: "date",
      typeInfo: "DateAsDate"
    }
```
```js
{ 2014-10-26T23:00:00.000Z originalTimezone: null }
```

**Comment by highsource** [comment]
Could you maybe post a working example? I'm not quite sure what the best way to solve this would be. 

In principle, you can implement and configure your own simple types. Jsonix includes a number of types, but you can easily extend it to your purposes.

**Comment by davidspiess** [comment]
I looked into this again, sorry for the delay. The underlying problem is https://github.com/nodejs/node/issues/4230, so i don't think there is anything to do on your side.
