### ISSUE TITLE
version of generated JSON Schema

### ISSUE THREAD

**Issue by crazynet** [highsource/jsonix#196]
Please let me know which JSON schema version is the generated one compliant to.
Draft-04 or Draft-06.
I dont see the generated JSON Schema contains that information, please help.

**Comment by highsource** [comment]
Draft-04. Development was based on the attached book.

Are there important differences between Draft-04 and Draft-06? Is it important to output version information? How?

[UnderstandingJSONSchema.pdf](https://github.com/highsource/jsonix/files/2079204/UnderstandingJSONSchema.pdf)

**Comment by crazynet** [comment]
Actually we needed the draft version to which the json schema is compliant is also an important information that can be part of auto generation.
It is important that being at server side we are planning to use json schema as a contract, so the client side will also be able to know which version of the json schema libraries they need to use.
