### ISSUE TITLE
Node.js Scripts test failing on install

### ISSUE THREAD

**Issue by clymbon** [highsource/jsonix#213]
Just downloaded jsonix from https://github.com/highsource/jsonix/archive/master.zip, unzipped it, and then ran mvn in the top-level directory.  (Please let me know if I'm missing some steps there.)

Seems to make some progress, but then fails with:

```
FAILURES: 2/898 assertions failed (340ms)
npm ERR! Test failed.  See above for more details.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jsonix 2.4.2-SNAPSHOT:
[INFO] 
[INFO] Jsonix ............................................. SUCCESS [  0.716 s]
[INFO] Jsonix Scripts ..................................... SUCCESS [ 10.015 s]
[INFO] Jsonix Node.js ..................................... SUCCESS [  0.013 s]
[INFO] Jsonix Node.js Scripts ............................. FAILURE [  4.234 s]
[INFO] Jsonix Node.js Tests ............................... SKIPPED
etc...
```

Unfortunately, despite the "See above for more details", I can't seem to find what's causing the failure. Tried running with various maven flags to get more diagnostics, but I'm not very good with maven, so I'm groping in the dark.  Would appreciate some help in debugging this.

Thanks!

**Comment by highsource** [comment]
Please try now. There were some problems with Windows vs. Linux line breaks.
