### ISSUE TITLE
XmlElementRef/JAXBElement issue

### ISSUE THREAD

**Issue by gitgabrio** [highsource/jsonix#225]
Hi all,
maybe it is related to this https://github.com/highsource/jsonix/issues/68, anyway:
I have a series of xsd that generates classes with some JAXBElemen<...> and List<JAXBElemen<...>> property, annotated as XmlElementRef.
I can not change the xsd and I could not find a way to override the binding.
Debugging Js-all.js I see that in the generated json, element of such properties are objects with a "name" and "value" property, with the "value" property being the "wrapped" element I need.
To give an idea:

` @XmlElementRef(name = "DMNDiagramElement", namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends DiagramElement>> dmnDiagramElement;`

This is the generated java class - DiagramElement is an abstract class with multipe implementation.

In the mapped json, every element of such "list" is an object whose name reflect what it is in the XmlElementRef and the value is the json representation of the actual DiagramElement.

Is this the expected behavior? Is there a way to fix/deal with that ?
Many thanks
Gabriele

**Comment by highsource** [comment]
It's a so-called [element reference property](https://github.com/highsource/jsonix/wiki/Properties#element-reference-property). So yes, it works as designed.

You can often get rid of element reference properties using the [Simplify plugin](https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin).

**Comment by gitgabrio** [comment]
Thanks for your help. Yes, it is exactly the element reference issue. I will look at the simplify plugin, but I'm also wondering if there is no way to customize the generated json mapper: I'll go again through documentation to see if I find something about it.
Best
Gabriele

**Comment by highsource** [comment]
Simplify plugin is exactly how you customize the mapping.
