### ISSUE TITLE
Compatibility with Browserify

### ISSUE THREAD

**Issue by pgiraud** [highsource/jsonix#27]
Jsonix cannot be bundled with Browserify.

I've tried to create a bundle with the following command:

```
browserify main.js -o bundle.js
```

The `main.js` file looks like the following:

```
var Jsonix = require('jsonix').Jsonix;
var context =  new Jsonix.Context([]);
```

The `bundle.js` file is created. However, when loaded in the browser, I
get the following error in my console:

```
Uncaught TypeError: Cannot read property 'apply' of undefined
```

The guilty line looks like the following:

```
return module.require.apply(module, arguments);
```

**Comment by bartvde** [comment]
a similar thing happens in webpack2, the code to load amdefine gets triggered see #171
