### ISSUE TITLE
ISODate format or Epoch time

### ISSUE THREAD

**Issue by imomin** [highsource/jsonix#48]
I am using jsonix to store data in nosql (mongodb). Problem is I cannot query data by date (less than or greater than). Is there a way to set a format to return date either in epoch time or ISODate format?
 
Disclaimer: I am new to nosql and and recently started using jsonix.

**Comment by highsource** [comment]
Yes, it is probably possible. I'll put an example together.
But first a question: what do you mean by *epoch time* and *ISODate format*, exactly?

My guesses are:

* *epoch time* - a number (integer) of milliseconds after 1970-01-01 and so on.
* *ISODate format* - a string like "2015-01-01T02:03:04"

Please confirm or give your examples.

**Comment by imomin** [comment]
Currently, the json for the date looks like {"year":2001,"month":10,"day":31,"hour":8,"minute":15,"second":0,"fractionalSecond":0,"timezone":0}
Instead, I wondering if I can get date in the epoch (integer) or ISODate format like your comment.

**Comment by highsource** [comment]
Yes, possible. I'm working on an example right now.

https://github.com/highsource/jsonix/wiki/Types#defining-custom-simple-types

**Comment by imomin** [comment]
Following tweak worked for me. In the js file which is generated from .xsd. I changed typeInfo from Calender to DateTime. 
          {
            name: 'dateTimeCreation',
            typeInfo: 'DateTime'
          }, {
            name: 'dateTimeChange',
            typeInfo: 'DateTime'
          }
Which returns the date in following format "2001-05-31T08:15:00.000Z". Which is queryable in MongoDB.

**Comment by highsource** [comment]
Documentation:

https://github.com/highsource/jsonix/wiki/Types#defining-custom-simple-types

Example:

https://github.com/highsource/jsonix/blob/master/nodejs/tests/basic/tests/gh48.js

```javascript
var DateTimeTimestamp = new (Jsonix.Class(Jsonix.Schema.XSD.DateTime, {
	// Strictly speaking name and typeName are not necessary here as they're
	// inherited from Jsonix.Schema.XSD.DateTime
	name : 'DateTime',
	typeName : Jsonix.Schema.XSD.qname('dateTime'),
	parse : function(text, context, input, scope) {
		Jsonix.Util.Ensure.ensureString(text);
		var date = Jsonix.Schema.XSD.DateTime.prototype.parse.apply(this,
				arguments);
		return date.getTime();
	},
	print : function(value, context, output, scope) {
		Jsonix.Util.Ensure.ensureInteger(value);
		var date = new Date(value);
		var text = Jsonix.Schema.XSD.DateTime.prototype.print.apply(this, [
				date, context, output, scope ]);
		return text;
	},
	CLASS_NAME : 'Timestamp'
}))();
var Mapping = {
	name : "Mapping",
	typeInfos : [ DateTimeTimestamp ],
	elementInfos : [ {
		elementName : 'dateTime',
		typeInfo : 'DateTime'
	} ]
};
```

**Comment by highsource** [comment]
Continued in #49. You'll be able to use the `DateTimeTimestamp` and get an integer then.
