### ISSUE TITLE
Allow passing string as element name

### ISSUE THREAD

**Issue by highsource** [highsource/jsonix#52]
See tomkralidis/csw4js#1.

Currently element references require an object like this:

```xml
{
        "namespaceURI": "http://www.opengis.net/cat/csw/2.0.2",
        "localPart": "GetRecords",
        "prefix": "csw"
}
```

This is too verbose. If the `csw` prefix [is already defined](https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Your-JavaScript-Program#namespace-prefixes), then it should be enough to write

```
'csw:GetRecords'
```

instead. Or `'{http://www.opengis.net/cat/csw/2.0.2}GetRecords'` or `'{http://www.opengis.net/cat/csw/2.0.2}csw:GetRecords'`.

Good question what to do on unmarshalling. Return string? Or object like now? Or have an option to switch it? Which namespace prefix to use?

**Comment by tomkralidis** [comment]
+1 for allowing option.

**Comment by highsource** [comment]
@tomkralidis Yes, option is probably the safest. Backwards compatibility and so on.

**Comment by highsource** [comment]
Started the documentatione here:

https://github.com/highsource/jsonix/wiki/Qualified-Names

**Comment by highsource** [comment]
Due to #56, I've decided not to implement QName -> string on unmarshalling for element references. The [simplified mappings style](https://github.com/highsource/jsonix/wiki/Simplified-Mapping-Style) solves this perfectly from my PoV.
