### ISSUE TITLE
Declaring a namespace/prefix mapping with the prefix '' generates xmlns:xmlns

### ISSUE THREAD

**Issue by ximex** [highsource/jsonix#62]
It isn't possible to define a namespace without a prefix.
```javascript
namespacePrefixes: {
  'http://ris.bka.gv.at/Search/1.3/OGD': '',
  'http://www.w3.org/2001/XMLSchema-instance': 'xsi'
}
```

 It adds
`xmlns:xmlns="http://ris.bka.gv.at/Search/1.3/OGD"`
but it should be only
`xmlns="http://ris.bka.gv.at/Search/1.3/OGD"`

ximex/ris-bka#4

**Comment by highsource** [comment]
To help it get resolved faster, could you please PR a test case here:

https://github.com/highsource/jsonix/blob/master/nodejs/tests/basic/tests/xmlns.js

**Comment by highsource** [comment]
http://jsfiddle.net/lexi/q89e13sy/

**Comment by highsource** [comment]
@ximex Should be fixed now, please check the latest scripts:

https://github.com/highsource/jsonix/tree/master/dist

**Comment by ximex** [comment]
@highsource it works. could you do a npm release or do you wait to fix the other bugs?

**Comment by highsource** [comment]
Released:

* https://github.com/highsource/jsonix/releases/tag/2.1.4
* https://www.npmjs.com/package/jsonix

**Comment by ximex** [comment]
thx
