### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by juanmav** [highsource/jsonix#66]
Hi all,

Maybe would good to have a changelog ? At the moment I am working with version 2.1.2 but when I update to the 2.1.5 something breaks in my code. I Think with a changelog I can find the problem by myself (possibly it is a trivial error).

Thanks in advance
JM

**Comment by highsource** [comment]
Changes are documented in release notes per version: https://github.com/highsource/jsonix/releases

Normally I try to mind if there were any backwards-incompatible changes and upgrade the version accordingly. So if anything broke between 2.1.2 and 2.1.5, it is a bug.

You can see the specific changes here:

https://github.com/highsource/jsonix/compare/2.1.2...master

I'm not sure if I can really provide a changelog. Either I know of changes and thought about backwards compatibility - then it is in the release notes per version. Or I've made a mistake and missed the incompatibility - but in this case an extra changelog won't help.

**Comment by juanmav** [comment]
Ok, perfect. 

Thanks!
