### ISSUE TITLE
date bug in new version 2.2.0

### ISSUE THREAD

**Issue by ximex** [highsource/jsonix#76]
https://travis-ci.org/ximex/ris-bka/jobs/57329376
Error Message:
Uncaught Error: Value [] does not match dateTime, date or time patterns.

If i change back to version 2.1.4 all works fine:
https://github.com/ximex/ris-bka/commit/a6fc031f1c4aad166e734ffc2d22e42a2467e538

**Comment by highsource** [comment]
Please send be a pull request here:

* https://github.com/highsource/jsonix-support/tree/master/r/ris-bka

What I essentially need is a sample document and the mappings you generate.

**Comment by ximex** [comment]
https://github.com/highsource/jsonix-support/pull/4

**Comment by highsource** [comment]
You'd ultimately need #72 for the correct roundtrip. At the moment I've fixed this by unmarshalling empty strings as `null`s.
