### ISSUE TITLE
in simplified mode, why is casing changed?

### ISSUE THREAD

**Issue by bartvde** [highsource/jsonix#79]
E.g. why is it capability and not Capability?

![screen shot 2015-04-21 at 11 46 31](https://cloud.githubusercontent.com/assets/319678/7249641/1c42ed3c-e81c-11e4-9cbd-b7df140bda3e.png)

**Comment by highsource** [comment]
Changes from what? From standard mode? Don't think so, the property is
probably called `capability` there as well:
https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/WMS_1_3_0.js#L380

Simplified mode only applies to element references. Where in standard mode
you have { name: <name>, value: <value> }, in the simplified mode you'll
get { <name> : <value> }.

**Comment by bartvde** [comment]
Ah you're right, so then it's just a different approach than the ol3 parsers take, where they name exactly the casing as in the XML.
