### ISSUE TITLE
Timezone sign must be positive for timezones like +05:00

### ISSUE THREAD

**Issue by highsource** [highsource/jsonix#82]

**Comment by highsource** [comment]
Currently the timezone for `+05:00` would be `-300`. Correct would have been `300`.

Planned for `2.3.x` as this is not backwards compatible.

**Comment by highsource** [comment]
This is correct now.

**Comment by shawnExplore** [comment]
Thanks for fixing this! Would this also explain why I am getting positive values (e.g. 420) for negative timezones (e.g. -07:00)?

**Comment by highsource** [comment]
If you mean pre-`2.3.0` then yes, this was the problem. With `2.3.0` and up this should no longer be the case. If you keep getting different-signed values, please report an issue.
