### ISSUE TITLE
Using the latest tags does not unmarshal Ogc filters

### ISSUE THREAD

**Issue by juanmav** [highsource/jsonix#84]
Hi, 

I am trying to update Ows.js lib to the latest version of Jsonix (2.2.1), Ogc-schemas (2.2.0) and w3c-schemas (1.1.0) but when Jsonix unmarshall an XML the return Javascript Object has the ogc:filter broken.

I made a little jsfiddle https://jsfiddle.net/juanmav/2cmjzj4f/

Any ideas ?

Thanks 
JM

**Comment by highsource** [comment]
This is the problem:

https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/CSW_2_0_2.js#L820

**Comment by highsource** [comment]
This is an `ogc-schemas` problem. The "any element" property there does not allow typed objects. This has to be customized.

Continued in highsource/ogc-schemas#94.

**Comment by highsource** [comment]
Won't fix here, will be fixed in `ogc-schemas`.
