### ISSUE TITLE
How to set default namespace in marshalling process

### ISSUE THREAD

**Issue by htulipe** [highsource/jsonix#87]
Hi,

I put a SOS XML message through an SOS 1.0.0 unmarshaller and got the following JSON:

    {
      "name": {
        "namespaceURI": "http://www.opengis.net/sos/1.0",
        "localPart": "GetFeatureOfInterest",
        "prefix": "",
        "key": "{http://www.opengis.net/sos/1.0}GetFeatureOfInterest",
        "string": "{http://www.opengis.net/sos/1.0}GetFeatureOfInterest"
      },
      "value": {
        "TYPE_NAME": "SOS_1_0_0.GetFeatureOfInterest",
        "service": "SOS",
        "version": "1.0.0",
        "featureOfInterestId": [
          "http://mysite.com/sos/featureOfInterest/300",
          "http://mysite.com/sos/featureOfInterest/190",
          "http://mysite.com/sos/featureOfInterest/111",
          "http://mysite.com/sos/featureOfInterest/3"
        ]
      }
    }

I would like now to marshall it back to XML. The output looks OK but the parent element `GetFeatureOfInterest` is namespaced, something like:

    <p0:GetFeatureOfInterest xmlns:p0="http://www.opengis.net/sos/1.0">...</p0:GetFeatureOfInterest>

How could I tell the marshaller to use default namespace. I would like an output like this:

    <GetFeatureOfInterest xmlns="http://www.opengis.net/sos/1.0">...</GetFeatureOfInterest>

Thanks for having created Jsonix

**Comment by highsource** [comment]
Please see:

https://github.com/highsource/jsonix/wiki/Configuring-Namespace-Prefixes

Please try "http://www.opengis.net/sos/1.0" : "" mapping.

"http://www.opengis.net/sos/1.0" : "sos" should work in any case.

**Comment by htulipe** [comment]
I have to use default namespace because of the SOS backend I am using, it does not seems to like when the sos namespace is prefixed.

Thanks for the quick answer, it worked.
