### ISSUE TITLE
Bug in Jsonix.Util.Type.isEqual

### ISSUE THREAD

**Issue by htulipe** [highsource/jsonix#88]
If the marshalled xml contains a `length` tag ([this one](http://schemas.opengis.net/sampling/1.0.0/Examples/Profile1.xml) for instance), the output JSON will have a corresponding `length` attribute. Passing two of those objects to the `isEqual` method will result in a error at [this line](https://github.com/highsource/jsonix/blob/21baad4eecc4056b0b1495d6f435d8df5a7cd5f7/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Util/Type.js#L117) because the code relies on the `length` attribute to detect arrays.

**Comment by highsource** [comment]
Hm, I think, this code:

```
a.length && (a.length !== b.length)
```

should work, regardless if this is an array or not. If it's array - no problem, if not then both objects must have the `length` property.

**Comment by highsource** [comment]
Ah, OK. Won't work if `length` is an object, for instance.

**Comment by highsource** [comment]
Right, this should be `Jsonix.Util.Type.isArray(a) && (a.length !== b.length)`, but then there's an issue with DOM elements.

**Comment by htulipe** [comment]
What kind of issue?

**Comment by highsource** [comment]
If the JS structure contains DOM elements or nodes, `isEqual` goes in infinite recursion (since DOM structures are cyclic). `isEqual` must consider DOM nodes and compare them somehow. Probably serialize as strings and then compare strings.

**Comment by htulipe** [comment]
Indeed, I could reproduce that with either [Borehole1.xml](http://schemas.opengis.net/sampling/1.0.0/Examples/Borehole1.xml) or [Profile1.xml](http://schemas.opengis.net/sampling/1.0.0/Examples/Profile1.xml) (I don't remember which one)

**Comment by highsource** [comment]
`Borehole1.xml`, I think. Took me 1h yesterday, the test was failing with just printing `undefined`.
In the particular case I think this can be workarounded by adding mappings for the part that was overtaken as DOM. It's called "lax" processing. If Jsonix knows the mapping, for the "lax" element, it will be parsed using that mapping otherwise overtaken as DOM.

This issue is nevertheless a problem, will be fixed.

**Comment by highsource** [comment]
Should be fixed now. `isEqual` checks for nodes and arrays now.
