### ISSUE TITLE
getElementInfo fails on elements containing namespace value

### ISSUE THREAD

**Issue by yashutanna** [highsource/jsonix#98]
Hi

Im struggling to marshal a json object to XML and suspect a problem in the getElementInfo() method

the line ```var scopedElementInfo = scopedElementInfos[name.key];``` will fail for elements that have a namespace associated with it. for example, 

```scopedElementInfos = {
    '{namespace}someElement' :{...}
}```

```name.key = 'someElement'```

hence ```scopedElementInfo[name.key]``` is undefined after the above line in function getElementInfo()

**Comment by highsource** [comment]
Could you please submit a repro case?

**Comment by yashutanna** [comment]
thanks for the prompt reply

please see a jsFiddle here: https://jsfiddle.net/7gbrjmf0/

**Comment by highsource** [comment]
Here you go:
https://jsfiddle.net/7gbrjmf0/2/

* You needed to specify the "simplified" mapping style, see here: https://github.com/highsource/jsonix/wiki/Mapping-Styles
* You have to specify the namespace prefix, as mapped (`bar:SickNote`)
* Few minor things with dates

**Comment by yashutanna** [comment]
Awesome! thanks for that. 

Just one more thing. The array of ```DiagnosisCode``` Objects isn't pulling through in the ```SickNoteDiagnosis``` array

I checked the xsds, and seems like it's fine on that end, mapping states it as a collection so that looks fine too.

thanks again for your prompt reply

**Comment by highsource** [comment]
Please file another issue on that, with a minimal repro case.

**Comment by highsource** [comment]
I'm closing this one as it is resolved. Please file another issue for your `DiagnosisCode` problem.
