### ISSUE TITLE
Better documentation for running on node.js

### ISSUE THREAD

**Issue by coderextreme** [highsource/jsonix#99]
Please provide better documentation for running with node.js.  So far I've only been able to run in the browser.  I think amdefine may be the issue, but I'm not sure.  That is, needed requires, defines, packages.json entries, etc.

**Comment by highsource** [comment]
I've added a document on that:

https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Node.js-Programs

Please take a look and give feedback. Anything specific you're missing? You can correct it in Wiki directly

**Comment by coderextreme** [comment]
> On Sep 4, 2015, at 2:33 AM, Alexey Valikov <notifications@github.com> wrote:
> 
> I've added a document on that:
> 
> https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Node.js-Programs <https://github.com/highsource/jsonix/wiki/Using-Jsonix-in-Node.js-Programs>
> Please take a look and give feedback. Anything specific you're missing? You can correct it in Wiki directly
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/highsource/jsonix/issues/99#issuecomment-137665765>.
> 
Repository is: https://github.com/coderextreme/x3djson <https://github.com/coderextreme/x3djson>

$ cat bindings.xjb 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jaxb:bindings version="2.1" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<jaxb:bindings schemaLocation="x3d-3.4.xsd" node="/xs:schema">
                <jaxb:globalBindings typesafeEnumMaxMembers="600"/>
	</jaxb:bindings>
</jaxb:bindings>


$ java -jar node_modules/jsonix/lib/jsonix-schema-compiler-full.jar -generateJsonSchema -compact -logLevel TRACE -d mappings x3d-3.4.xsd -p x3djson -b bindings.xjb


##### Here’s the file I’m having difficulty with:


$ cat js/generatex3djson.js 
var Jsonix = require('jsonix').Jsonix;
var x3djsonSchema = require('../mappings/x3djson.jsonschema').x3djson;

var context = new Jsonix.Context([x3djson]);

var unmarshaller = context.createUnmarshaller();

unmarshaller.unmarshalURL('HelloWorld.x3d',
    function (unmarshalled) {
        document.write(JSON.stringify(unmarshalled, null, "  "));
    });



$ node generatex3djson.js 
/Users/johncarlson/Source/x3djson/mappings/x3djson.jsonschema:3
    "id":"#",
        ^
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/johncarlson/Source/x3djson/js/generatex3djson.js:2:21)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)

**Comment by highsource** [comment]
You should be loading the generated mappings, not the generated JSON Schema:

```
var x3djson = require('../mappings/x3djson.js').x3djson;
```

**Comment by coderextreme** [comment]
$ cat generatex3djson.js 
var Jsonix = require('jsonix').Jsonix;
var x3djson = require('../mappings/x3djson.js').x3djson;

var context = new Jsonix.Context([x3djson]);

var unmarshaller = context.createUnmarshaller();

unmarshaller.unmarshalURL('HelloWorld.x3d',
    function (unmarshalled) {
        console.log(JSON.stringify(unmarshalled, null, "  "));
    });



$ node generatex3djson.js 

/Users/johncarlson/Source/x3djson/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:292
        throw "Protocol not supported.";
        ^
Protocol not supported.

**Comment by highsource** [comment]
HelloWorld.x3d is obviously not an absolute URL. Use an absolute URL or unmarshalFile in Node.js.

> Am 04.09.2015 um 15:07 schrieb John Carlson <notifications@github.com>:
> 
> HelloWorld.x3d

**Comment by coderextreme** [comment]
Thank you for your help.  I am unexperienced at node.  I am getting more experienced though.

Sorry you had to do all my debugging.

John

**Comment by highsource** [comment]
So I think we can close this.

**Comment by highsource** [comment]
@coderextreme And no problem at all, I was glad to help you get started.
